config/routes.rb
Rails.application.routes.draw do

  get 'mypage/index'
  get 'mypage',to: 'mypage#index'
  
  get 'login/index'
  post 'login/index'
  
  get 'homes/index'
  get 'user_registration/index'
  get 'user_registration',to: 'user_registration#index'
  post 'user_registration/index'
  post 'user_registration', to: 'user_registration#index'

  get 'user/index'
  get 'user',to: 'user#index'
  post 'user/index'
  post 'user', to: 'user#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :restaurants do
    resources :menus
  end

  root 'homes#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :menus, dependent: :destroy
  validates :r_name, presence: true
  validates :address, presence: true
  validates :genre, presence: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    # sessionをリセットする(testでつかう)
    session[:user] = nil
    if session[:user] == nil
      redirect_to login_index_path
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index

    if request.post? then
      @name = params['inputName']
      @password = params['inputPassword']
      @u = User.find_by(u_name: @name)
      if !(@u.nil?)
        if @password == @u.passward
          session[:user] = @u.u_name
          redirect_to restaurants_path
        else
          @msg = "パスワードが違います"
        end
      else
        @msg = "該当するユーザーが存在しません"
      end

    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController

  def index

    if session[:user] == nil
      redirect_to login_index_path
    end
    @user = User.find_by(u_name:session[:user])


    @tamagoFlag = false
    @komugiFlag = false
    @milkFlag = false
    @kaniFlag = false
    @ebiFlag = false
    @sobaFlag = false
    @peanutFlag = false

    @user.allergy.split(",").each do |allergy|
      if (allergy == "卵")
        @tamagoFlag = true
      end
      if (allergy == "小麦")
        @komugiFlag = true
      end
      if (allergy == "乳")
        @milkFlag = true
      end
      if (allergy == "かに")
        @kaniFlag = true
      end
      if (allergy == "えび")
        @ebiFlag = true
      end
      if (allergy == "そば")
        @sobaFlag = true
      end
      if (allergy == "落花生")
        @peanutFlag = true
      end
    end

  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    if session[:user]
      @user = User.find_by(u_name:session[:user])
    else
      redirect_to login_index_path
    end

    @restaurants = Restaurant.all.order(created_at: 'asc')

    @wariai = []
    @percentage = []

    @restaurants.each do |restaurant|
      menu_count = restaurant.menus.size
      count = 0
      restaurant.menus.each do |menu|
        ma = menu.allergy.split(",") #ma -> menu allergy
        ma.each do |m|
          flag = false
          ua = @user.allergy.split(",") #ua -> user a;lergy
          ua.each do |u|
            if(m == u && flag == false)
              count += 1
              flag = true
              break
            end
          end
          if flag == true
            break
          end
        end
      end
      @wariai.push(menu_count.to_s + "品中" + count.to_s + "品にアレルギー成分が含まれています")
      @percentage.push(((count.to_f / menu_count.to_f).round(1)*100).to_i)
    end
  end

    def show
      if session[:user] == nil
        redirect_to login_index_path
      end
      @usr = User.find_by(u_name:session[:user])
      @restaurant = Restaurant.find(params[:id])
      @allergy = @usr.allergy.split(",")
    end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  #ユーザのデータベースから情報を取得
  def index
    @title = "UserProfile"
    @userdata = User.all

    if request.post? then

      if params['inputName'] then
        @name = params['inputName']
      end

      if params['inputPassward'] then
        @passward = params['inputPassward']
      end
  
      @userdata = User.where "u_name = ? and passward = ?",params['inputName'],params['inputPassward']
      
    end

  end

end

app/controllers/user_registration_controller.rb
class UserRegistrationController < ApplicationController
  def index
    @title = "ユーザー登録"
    @name = '名前を入力して下さい'
    @passward = 'パスワードを入力して下さい'
    @gender = "性別を選択して下さい"
    @old = "年代を選択して下さい"
    @allergy = "アレルギーを選択して下さい"
    if request.post? then

      if params['inputName'] then
        @name = params['inputName']

      end

      if params['inputPassward'] then
        @passward = params['inputPassward']

      end

      if params['gender'] then
        @gender = params['gender']
      end

      if params['old'] then
        @old = params['old']
      end

      if params['Allergylist'] then
        @allergy = ""
        #di1にアレルギー名　di2に0か１（１なら選択された）
        params['Allergylist'].each do |di1,di2|
          if di2 == "1"
          @allergy += di1
          @allergy += ","
          end
        end
        @allergy.chop!
        if @allergy == ""
          @allergy = "アレルギーを選択して下さい"
        end
      end

      user = User.new(u_name: @name,passward: @passward,sex: @gender, age: @old, allergy: @allergy)
      user.save

    else
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_registration_helper.rb
module UserRegistrationHelper
end

app/views/homes/index.html.erb
<h2>Hello World!!</h2>
<%= link_to "飲食店一覧", restaurants_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Allergy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to image_tag('logo.png', class: 'logo'), root_path %>
    <%= link_to image_tag('icon.png', class: 'icon'), mypage_index_path %>
    <%= yield %>
  </body>
</html>

app/views/layouts/header.html.erb
<nav class="white">
    <div class="header">
    
      <ul id="links" class="left hide-on-med-and-down">
          <li><%= link_to image_tag('logo.png', class: 'logo',:size => "60x60"), root_path %></li>
          <li><%= link_to "SHOW", restaurants_path,:style=>"color:black;"%></li>
          <li><%= link_to "MAP",user_registration_path,:style=>"color:black;" %></li>
      </ul>
     

      <ul id="links" class="right hide-on-med-and-down">
          <li><%= link_to image_tag('user.png', class: 'user',:size => "60x60"), mypage_path %></li>
          <li><%= link_to image_tag('bell.png', class: 'user',:size => "60x60") %></li>
      </ul>
    </div>
</nav>

app/views/layouts/mypage.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render template: 'layouts/header'%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'mypage','data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/restaurants.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'restaurants','data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'pinkmain','data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<h2>ログイン</h2>

<%= form_tag(controller: "login", action:"index") do %>

  <p>お名前</p>
  <%= text_field_tag("inputName") %>
  <br>
  <p>パスワード</p>
  <%= password_field_tag("inputPassword") %>
  <br>
  <%= submit_tag("Login")%>

<%= link_to '新規登録', user_registration_path %>
<% end %>
<%= @msg %>

app/views/mypage/index.html.erb
<%= render template: 'layouts/header'%>

<div class = "main"> 

    <div class="name">
        <%= @user.u_name + "様" %>
    </div>

    <div class="age">
        <%= @user.age%>
    </div>

    <div class="sex">
        <%= @user.sex%>
    </div>

    <div class="text">
        <%= "該当アレルギー　一覧"%>
    </div>

    <div class="tamago">
        <% if @tamagoFlag == false %>
            <%= image_tag("blackimage.png", class: 'tamago',:size => "60x60")%>
        <% else %>
            <%= image_tag("tamago.png", class: 'tamago',:size => "60x60")%>
        <% end %>
    </div>

    <div class="komugi">
        <% if @komugiFlag == false %>
            <%= image_tag("blackimage.png", class: 'komugi',:size => "60x60")%>
        <% else %>
            <%= image_tag("komugi.png", class: 'komugi',:size => "60x60")%>
        <% end %>
    </div>

    <div class="milk">
        <% if @milkFlag == false %>
            <%= image_tag("blackimage.png", class: 'milk',:size => "60x60")%>
        <% else %>
            <%= image_tag("milk.png", class: 'milk',:size => "60x60")%>
        <% end %>
    </div>

    <div class="tamgo">
        <% if @kaniFlag == false %>
            <%= image_tag("blackimage.png", class: 'kani',:size => "60x60")%>
        <% else %>
            <%= image_tag("kani.png", class: 'kani',:size => "60x60")%>
        <% end %>
    </div>

    <div class="tamgo">
        <% if @ebiFlag == false %>
            <%= image_tag("blackimage.png", class: 'ebi',:size => "60x60")%>
        <% else %>
            <%= image_tag("ebi.png", class: 'ebi',:size => "60x60")%>
        <% end %>
    </div>

    <div class="tamgo">
        <% if @sobaFlag == false %>
            <%= image_tag("blackimage.png", class: 'soba',:size => "60x60")%>
        <% else %>
            <%= image_tag("soba.png", class: 'soba',:size => "60x60")%>
        <% end %>
    </div>

    <div class="tamgo">
        <% if @peanutFlag == false %>
            <%= image_tag("blackimage.png", class: 'peanut',:size => "60x60")%>
        <% else %>
            <%= image_tag("peanut.png", class: 'peanut',:size => "60x60")%>
        <% end %>
    </div>
    
</div>

app/views/restaurants/index.html.erb
<%= render template: 'layouts/header'%>

<div class = main>

  <h2>
    Restaurant List
  </h2>
  
  <ul>
    <% i = 0 %>
    <% @restaurants.each do |r| %>
    
    <li>
      <%= link_to r.r_name, restaurant_path(r) %>
      <%= r.address %>
      <%= r.genre %>
      <%= @percentage[i]%>
    </li>

    <%= @wariai[i] %>
    <% i += 1 %>
    <% end %>
  </ul>

</div>

app/views/restaurants/show.html.erb
<%= render template: 'layouts/header'%>

<div class = main>

  <h2><%= @restaurant.r_name %></h2>
  <ul>
    <li>
      <%= @restaurant.address %>
    </li>
    <li>
      <%= @restaurant.genre %>
    </li>
  </ul>

  <h3>メニュー</h3>


  <table>
          <thead>
            <tr>
                <th>image</th>
                <th>Name</th>
                <th>Item Name</th>
                <th>Item Price</th>
            </tr>
          </thead>

      <tbody>
      <% @restaurant.menus.each do |menu| %>


        <% m_all = menu.allergy.split(",") %>
        <% u_all = @allergy %>

        <% flag = false %>

        <% m_all.each do |m| %>
          <% u_all.each do |u| %>
            <% if m == u && flag == false %>
              <span style="background-color:red">
                <tr bgcolor = "#cccccc">
                    <td><%= image_tag("tamago.png", class: 'tamago',:size => "60x60")%></td>
                    <td><%= menu.m_name %></td>
                    <td><%= menu.allergy %></td>
                    <td><%= menu.price %></td>
                </tr>
              </span>
              <% flag = true %>
            <% end %>
          <% end %>
        <% end %>
        <% if flag == false %>
            <tr>
              <td><%= image_tag("tamago.png", class: 'tamago',:size => "60x60")%></td>
              <td><%= menu.m_name %></td>
              <td><%= menu.allergy %></td>
              <td><%= menu.price %></td>
            </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/user/index.html.erb
<h1><%= @title %></h1>

<%= form_tag(controller: "user", action:"index" ) do %>
	<br>
    <%= label_tag("Nametext", "お名前")  %>
    <%= text_field_tag("inputName") %>
    <br>

    <br>
    <%= label_tag("PassWardtext", "パスワード")  %>
    <%= text_field_tag("inputPassward") %>
    <br>

	<%= submit_tag("Click")%>
	<p><%=@name%></p>
	<p><%=@passward%></p>
	<table>
    	<tr>
			<th>Id</th><th>Name</th><th>passward</th><th>sex</th><th>age</th><th>allergy</th>
		</tr>
		<% @userdata.each do |obj| %>
		<tr>
        	<td><%= obj.id %></td>
			<td><%= obj.u_name %></td>
			<td><%= obj.passward %></td>
        	<td><%= obj.sex %></td>
        	<td><%= obj.age %></td>
        	<td><%= obj.allergy %></td>
		</tr>
		<% end %>
	</table>
<% end %>

app/views/user_registration/index.html.erb
<h1><%= @title %></h1>

<%= form_tag(controller: "user_registration", action:"index" ) do %>
    <br>
    <%= label_tag("Nametext", "お名前")  %>
    <%= text_field_tag("inputName") %>
    <br>

    <br>
    <%= label_tag("PassWardtext", "パスワード")  %>
    <%= password_field_tag("inputPassward") %>
    <br>

    <br>


    <br>
    <%= label_tag("labelSex", "性別")  %>
    <%= select_tag("old", options_for_select(['男性','女性','その他'])) %>

    <%= label_tag("labelOld", "年齢")  %>
    <%= select_tag("old", options_for_select(['10代未満', '10代', '20代','30代', '40代','50代', '60代','70代以上'])) %>
    <br>

    <%= label_tag("labelAllergy", "アレルギー")  %>
    <ul style="list-style-type:none;">
    <li><%= check_box "Allergylist", "卵" %>卵</li>
    <li><%= check_box "Allergylist", "小麦" %>小麦</li>
    <li><%= check_box "Allergylist", "乳" %>乳</li>
    <li><%= check_box "Allergylist", "かに" %>かに</li>
    <li><%= check_box "Allergylist", "えび" %>えび</li>
    <li><%= check_box "Allergylist", "そば" %>そば</li>
    <li><%= check_box "Allergylist", "落花生" %>落花生</li>

  </ul>

  <%= submit_tag("Click")%>
  <%= link_to 'ログインページへ', login_index_path %>

  <p><%= @name %></p>
  <p><%= @passward %></p>
  <p><%= @gender %></p>
  <p><%= @old %></p>
  <p><%= @allergy %></p>


<% end %>